/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPublishersRouteImport } from './routes/_authenticated/publishers'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPublishersIndexRouteImport } from './routes/_authenticated/publishers.index'
import { Route as AuthenticatedPublishersIdRouteImport } from './routes/_authenticated/publishers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishersRoute = AuthenticatedPublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishersIndexRoute =
  AuthenticatedPublishersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPublishersRoute,
  } as any)
const AuthenticatedPublishersIdRoute =
  AuthenticatedPublishersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPublishersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/publishers': typeof AuthenticatedPublishersRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/publishers/$id': typeof AuthenticatedPublishersIdRoute
  '/publishers/': typeof AuthenticatedPublishersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/publishers/$id': typeof AuthenticatedPublishersIdRoute
  '/publishers': typeof AuthenticatedPublishersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/publishers': typeof AuthenticatedPublishersRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/publishers/$id': typeof AuthenticatedPublishersIdRoute
  '/_authenticated/publishers/': typeof AuthenticatedPublishersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/performance'
    | '/publishers'
    | '/settings'
    | '/publishers/$id'
    | '/publishers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/performance'
    | '/settings'
    | '/publishers/$id'
    | '/publishers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/performance'
    | '/_authenticated/publishers'
    | '/_authenticated/settings'
    | '/_authenticated/publishers/$id'
    | '/_authenticated/publishers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publishers': {
      id: '/_authenticated/publishers'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof AuthenticatedPublishersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publishers/': {
      id: '/_authenticated/publishers/'
      path: '/'
      fullPath: '/publishers/'
      preLoaderRoute: typeof AuthenticatedPublishersIndexRouteImport
      parentRoute: typeof AuthenticatedPublishersRoute
    }
    '/_authenticated/publishers/$id': {
      id: '/_authenticated/publishers/$id'
      path: '/$id'
      fullPath: '/publishers/$id'
      preLoaderRoute: typeof AuthenticatedPublishersIdRouteImport
      parentRoute: typeof AuthenticatedPublishersRoute
    }
  }
}

interface AuthenticatedPublishersRouteChildren {
  AuthenticatedPublishersIdRoute: typeof AuthenticatedPublishersIdRoute
  AuthenticatedPublishersIndexRoute: typeof AuthenticatedPublishersIndexRoute
}

const AuthenticatedPublishersRouteChildren: AuthenticatedPublishersRouteChildren =
  {
    AuthenticatedPublishersIdRoute: AuthenticatedPublishersIdRoute,
    AuthenticatedPublishersIndexRoute: AuthenticatedPublishersIndexRoute,
  }

const AuthenticatedPublishersRouteWithChildren =
  AuthenticatedPublishersRoute._addFileChildren(
    AuthenticatedPublishersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPublishersRoute: typeof AuthenticatedPublishersRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPublishersRoute: AuthenticatedPublishersRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
