/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPublishersRouteImport } from './routes/_authenticated/publishers'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedFunnelRouteImport } from './routes/_authenticated/funnel'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreativeRouteImport } from './routes/_authenticated/creative'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedPublishersIndexRouteImport } from './routes/_authenticated/publishers.index'
import { Route as AuthenticatedPublishersIdRouteImport } from './routes/_authenticated/publishers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishersRoute = AuthenticatedPublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunnelRoute = AuthenticatedFunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreativeRoute = AuthenticatedCreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishersIndexRoute =
  AuthenticatedPublishersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPublishersRoute,
  } as any)
const AuthenticatedPublishersIdRoute =
  AuthenticatedPublishersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPublishersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/creative': typeof AuthenticatedCreativeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funnel': typeof AuthenticatedFunnelRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/publishers': typeof AuthenticatedPublishersRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/publishers/$id': typeof AuthenticatedPublishersIdRoute
  '/publishers/': typeof AuthenticatedPublishersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/creative': typeof AuthenticatedCreativeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funnel': typeof AuthenticatedFunnelRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/publishers/$id': typeof AuthenticatedPublishersIdRoute
  '/publishers': typeof AuthenticatedPublishersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/creative': typeof AuthenticatedCreativeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/funnel': typeof AuthenticatedFunnelRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/publishers': typeof AuthenticatedPublishersRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/publishers/$id': typeof AuthenticatedPublishersIdRoute
  '/_authenticated/publishers/': typeof AuthenticatedPublishersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/compliance'
    | '/creative'
    | '/dashboard'
    | '/funnel'
    | '/outreach'
    | '/performance'
    | '/publishers'
    | '/settings'
    | '/publishers/$id'
    | '/publishers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/compliance'
    | '/creative'
    | '/dashboard'
    | '/funnel'
    | '/outreach'
    | '/performance'
    | '/settings'
    | '/publishers/$id'
    | '/publishers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/campaigns'
    | '/_authenticated/compliance'
    | '/_authenticated/creative'
    | '/_authenticated/dashboard'
    | '/_authenticated/funnel'
    | '/_authenticated/outreach'
    | '/_authenticated/performance'
    | '/_authenticated/publishers'
    | '/_authenticated/settings'
    | '/_authenticated/publishers/$id'
    | '/_authenticated/publishers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publishers': {
      id: '/_authenticated/publishers'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof AuthenticatedPublishersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funnel': {
      id: '/_authenticated/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof AuthenticatedFunnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creative': {
      id: '/_authenticated/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof AuthenticatedCreativeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publishers/': {
      id: '/_authenticated/publishers/'
      path: '/'
      fullPath: '/publishers/'
      preLoaderRoute: typeof AuthenticatedPublishersIndexRouteImport
      parentRoute: typeof AuthenticatedPublishersRoute
    }
    '/_authenticated/publishers/$id': {
      id: '/_authenticated/publishers/$id'
      path: '/$id'
      fullPath: '/publishers/$id'
      preLoaderRoute: typeof AuthenticatedPublishersIdRouteImport
      parentRoute: typeof AuthenticatedPublishersRoute
    }
  }
}

interface AuthenticatedPublishersRouteChildren {
  AuthenticatedPublishersIdRoute: typeof AuthenticatedPublishersIdRoute
  AuthenticatedPublishersIndexRoute: typeof AuthenticatedPublishersIndexRoute
}

const AuthenticatedPublishersRouteChildren: AuthenticatedPublishersRouteChildren =
  {
    AuthenticatedPublishersIdRoute: AuthenticatedPublishersIdRoute,
    AuthenticatedPublishersIndexRoute: AuthenticatedPublishersIndexRoute,
  }

const AuthenticatedPublishersRouteWithChildren =
  AuthenticatedPublishersRoute._addFileChildren(
    AuthenticatedPublishersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedCreativeRoute: typeof AuthenticatedCreativeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFunnelRoute: typeof AuthenticatedFunnelRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPublishersRoute: typeof AuthenticatedPublishersRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedCreativeRoute: AuthenticatedCreativeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFunnelRoute: AuthenticatedFunnelRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPublishersRoute: AuthenticatedPublishersRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
